defaults: &defaults
  docker:
  - image: golang:1.11.4
  working_directory: /go/src/github.com/cloud-ca/terraform-provider-cloudca

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
    - checkout
    - save_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - /go/src/github.com/cloud-ca/terraform-provider-cloudca

  lint:
    <<: *defaults
    docker:
    - image: quay.io/kubermatic/gometalinter:latest
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: make lint

  build:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: make init
    - run: make build

workflows:
  version: 2
  build:
    jobs:
    - checkout:
        filters:
          tags:
            only: /v.*/
    - lint:
        requires:
        - checkout
        filters:
          tags:
            only: /v.*/
    - build:
        requires:
        - checkout
        filters:
          tags:
            only: /v.*/
