name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Verify 'vendor' dependencies
      run: make verify

    - name: Check formatting of go files
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make goimports checkfmt

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.37.0
        # Optional: if set to true then the action will use pre-installed Go.
        skip-go-installation: true
        # Optional: show only new issues if it's a pull request. default is false
        # only-new-issues: true
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build binary for current OS/ARCH
      run: make build
