name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Verify 'vendor' dependencies
      run: make verify

    - name: Check formatting of go files
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make goimports checkfmt

    - name: Run linters
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make golangci lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run tests
      run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binary for current OS/ARCH
      run: make build
