name: prerelease

on:
  push:
    tags:
      - 'v*.*.*-*'

jobs:
  prerelease:
    name: Pre-Release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.4.0

    - name: Import GPG key
      id: import_gpg
      uses: hashicorp/ghaction-import-gpg@v2.1.0
      env:
        # These secrets will need to be configured for the repository:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2.8.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist -f .goreleaser.prerelease.yml
      env:
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        # GitHub sets this automatically
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
